{% set data = load_setup_py_data() %}

package:
  name: jupyterlab_{{ cookiecutter.project_slug }}
  version: {{ data.get('version') }}
  
source:
  path: ../

build:
  noarch: python
  entry_points:
    - {{ cookiecutter.project_slug }}-lab = jupyterlab_{{ cookiecutter.project_slug }}.labapp:main
    - {{ cookiecutter.project_slug }}-labextension = jupyterlab_{{ cookiecutter.project_slug }}.labextensionapp:main

requirements:
  build:
    - python
    - pip
    - nodejs >=8.0,<10.0
    - jupyterlab
  run:
    - python
    - jupyterlab

    # Python packages corresponding to extensions installed in build.sh
    - ipywidgets >=7.2
    - bqplot >=0.10.5

about:
  home: https://github.com/{{ cookiecutter.github_username }}/jupyterlab_{{ cookiecutter.project_slug }}
  license: BSD 3-Clause
  license_file: LICENSE
  summary: {{ data.get('description') }}
